version: "3"

networks:
  mafia-backend:

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - ./local/rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      - ./local/rabbitmq-logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mafia-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  janus:
    build:
      context: ./config/docker/janus
      dockerfile: Dockerfile
    entrypoint:
      ["wait-for-it.sh", "rabbitmq:15672", "--strict", "--timeout=300", "--"]
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    volumes:
      - ./config/janus:/usr/local/etc/janus
      - ./config/letsencrypt:/etc/letsencrypt
      - ./local/janus-logs/janus.log:/var/log/janus.log
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/janus/info"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mafia-backend
    restart: always

  janus-microservice:
    build:
      context: ./janus-microservice
      dockerfile: Dockerfile
    entrypoint: ["wait-for-it.sh", "rabbitmq:15672", "--strict", "--timeout=300", "--"]
    environment:
    - TEST=test
    ports:
      - 9229:9229
    depends_on:
      - rabbitmq
      - janus
    volumes:
      - ./janus-microservice:/usr/src/app
    networks:
      - mafia-backend
    command: npm run start:debug
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./local/postgres:/var/lib/postgresql/data

  app:
    build:
      context: ./mafia-server
      dockerfile: Dockerfile
    entrypoint:
      ["wait-for-it.sh", "rabbitmq:15672", "--strict", "--timeout=300", "--"]
    environment:
      - PORT=3000
    ports:
      - 3000:3000
      - 9230:9229
    depends_on:
      - rabbitmq
      - janus
      - postgres
    volumes:
      - ./mafia-server:/usr/src/app
    networks:
      - mafia-backend
    command: npm run start:debug
    restart: always
